services:
  - type: web
    name: instagram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi
    plan: free
    region: oregon
    build:
      pythonVersion: 3.11.9
